services:
  db:
    image: postgres:18
    container_name: xmlrpc_postgres18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xmlrpc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - xmlrpc_network

  xmlrpc_server:
    build: ./server
    container_name: xmlrpc_server
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/xmlrpc_db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    networks:
      - xmlrpc_network

  graphql_server:
    build: ./server
    container_name: graphql_server
    restart: always
    depends_on:
      - db
      - xmlrpc_server
    environment:
      DATABASE_URL: postgres://user:password@db:5432/xmlrpc_db
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: ["python", "graphql_server.py"]
    networks:
      - xmlrpc_network

volumes:
  pgdata:

networks:
  xmlrpc_network:
    driver: bridge
