version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: IS
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: IS
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_SERVER: mongo_container

      # Login no browser (http://localhost:8081)
      ME_CONFIG_BASICAUTH_USERNAME: IS
      ME_CONFIG_BASICAUTH_PASSWORD: 1234

  grpc_server:
    build: ./grpc_server
    container_name: grpc_python_server
    restart: always
    depends_on:
      - mongo
    ports:
      - "50051:50051"
    environment:
      MONGO_HOST: mongo_container
      MONGO_USER: IS
      MONGO_PASS: 1234
      MONGO_DB: salesdb
    volumes:
      - ./grpc_server:/app

volumes:
  mongo_data:
